### ISSUE TITLE
Computational Complexity of LPLR Algorithm in Relation to Finding W*

### ISSUE THREAD

**Issue by Pairshoe** [pilancilab/matrix-compressor#6]
Hi,

Great work!
I have been studying the LPLR algorithm and I have a question regarding the computational complexity mentioned.

The paper states that the computational complexity of the LPLR algorithm is $O(nmd)$. However, I am concerned about the complexity of the pseudo-inverse calculation step (for finding W*) within the algorithm, which is typically $O(m^2n)$ when using the Singular Value Decomposition (SVD). Given that this step can be computationally expensive, I would like to clarify the following points:
1. Does the stated complexity $O(nmd)$ include the complexity of calculating the pseudo-inverse?
2. If m≪d, is it correct to assume that the $O(m^2n)$ complexity of the pseudo-inverse is negligible compared to the $O(nmd)$ operations?
3. Are there any recommended approaches or approximations for reducing the computational load of the pseudo-inverse calculation within the LPLR framework?

Understanding these aspects is crucial for efficiently implementing the algorithm on large-scale datasets.
Thank you for your assistance!

**Comment by rajarshisaha95** [comment]
Hello,

Thanks for your query. Point 2 in your response is exactly the reason. We assume the sketch size to be much less than the dimension of the matrix, i.e., m << d. This is true for many real world matrices, and hence the O(nmd) dominates.

It is not necessary to compute the pseudo-inverse. Line 4 of Alg. 1 in our paper (https://openreview.net/pdf?id=rxsCTtkqA9) is a least squares problem and can also be solved using iterative methods (like conjugate gradient descent).

**Comment by Pairshoe** [comment]
Thanks for your response!
